name: Deploy Bicep Template

on:
  push:
    branches:
      - main  # Deploy on push to the main branch
  pull_request:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Setup Azure CLI
      uses: azure/cli@v1
      with:
        azcliversion: 2.30.0  # Specify the Azure CLI version

    - name: Login to Azure
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}  # Store your Azure credentials in GitHub secrets

    - name: Deploy Bicep template
      run: |
        az deployment sub create \
          -l northeurope \
          --template-file ./iac-resources/main.bicep
