name: Deploy Bicep Template

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  id-token: write
  contents: read
jobs:
  build-and-run:
    environment: DEV
    runs-on: ubuntu-latest
    steps:
      - name: Check repo
        uses: actions/checkout@v4
        with:
          repository: ${{ github.repository }}

      - name: Lint Bicep and Bicepparam files
        run: |
          az bicep install
          success="true"
          CHANGED_FOLDERS=$(git diff HEAD~1 --name-only | xargs dirname)
          echo "📂 Changed folders:"
          echo $CHANGED_FOLDERS
          FILES=$(find $CHANGED_FOLDERS \( -name "*.bicep" -o -name "*.bicepparam" \))
          echo "🔍 Files to lint:"
          echo $FILES
          for file in $FILES; do
          { # 'try' block
            echo "🎗️ Linting $file" && az bicep lint --file $file
          } || { # 'catch' block
            success="false"
          }
          done
          if [ "$success" = "false" ]; then
            echo "::error::❌ Linting of the Bicep files failed."
            exit 1;
          fi;

      - name: Azure login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Deploy Bicep template
        run: |
          az deployment sub create \
            -l northeurope \
            --template-file ../study-material/azure/bicep-templates/iac-resources/main.bicep
