name: Deploy Bicep Template

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  id-token: write
  contents: read
jobs:
  build:
    environment: DEV
    runs-on: ubuntu-latest
    steps:
      - name: Check repo
        uses: actions/checkout@v4
        with:
          repository: ${{ github.repository }}

      - name: Azure login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Azure CLI script
        uses: azure/cli@v2
        with:
          azcliversion: latest
          inlineScript: |
            az account show

      - name: Print current path
        run: ls -la -R

      - name: Find main.bicep file
        id: find_file
        run: |
          file_path=$(find . -name "main.bicep")
          if [ -z "$file_path" ]; then
            echo "main.bicep file not found"
            exit 1
          else
            echo "main.bicep file found at $file_path"
            echo "::set-output name=filepath::$file_path"
          fi

      - name: Deploy Bicep template
        run: |
          az deployment sub create \
            -l northeurope \
            --template-file ../azure/bicep-templates/iac-resources/main.bicep
